# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MoodMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoodMe
  pod 'ARCapture', :git => 'https://gitlab.com/seriyvolk83/arcapture.git'

end
